// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZhFJv7zU7A2wNQUfo2FlfEBe1th2RToU',
    appId: '1:94025684387:web:565f81af33e3c0e540f616',
    messagingSenderId: '94025684387',
    projectId: 'project2-70bfc',
    authDomain: 'project2-70bfc.firebaseapp.com',
    storageBucket: 'project2-70bfc.appspot.com',
    measurementId: 'G-QQJ5JV87W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-1bZzrp1ZiI0WslbNcp1ucb6eUbQvDzE',
    appId: '1:94025684387:android:029effffe7506a0c40f616',
    messagingSenderId: '94025684387',
    projectId: 'project2-70bfc',
    storageBucket: 'project2-70bfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWUO3T6lH7WV-1zhPPiU4hBKQAoA1ShWg',
    appId: '1:94025684387:ios:180795781b2543ee40f616',
    messagingSenderId: '94025684387',
    projectId: 'project2-70bfc',
    storageBucket: 'project2-70bfc.appspot.com',
    iosBundleId: 'com.example.portfolioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWUO3T6lH7WV-1zhPPiU4hBKQAoA1ShWg',
    appId: '1:94025684387:ios:180795781b2543ee40f616',
    messagingSenderId: '94025684387',
    projectId: 'project2-70bfc',
    storageBucket: 'project2-70bfc.appspot.com',
    iosBundleId: 'com.example.portfolioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZhFJv7zU7A2wNQUfo2FlfEBe1th2RToU',
    appId: '1:94025684387:web:7b173d2b4b77e00f40f616',
    messagingSenderId: '94025684387',
    projectId: 'project2-70bfc',
    authDomain: 'project2-70bfc.firebaseapp.com',
    storageBucket: 'project2-70bfc.appspot.com',
    measurementId: 'G-PVZKB0VQHM',
  );
}
